### ISSUE TITLE
Building from source failed at "ReferenceError: The given file: 'lib.es2018.asynciterable.d.ts' doesn't exist"

### ISSUE THREAD

**Issue by chenqy930** [wessberg/intl-relative-time-format#2]
Failed to build from the github downloaded source code. 
Run comand "npm run build", the error is:
```
[!] (plugin Typescript) ReferenceError: The given file: 'lib.es2018.asynciterable.d.ts' doesn't exist!
src/index.ts
ReferenceError: The given file: 'lib.es2018.asynciterable.d.ts' doesn't exist!
    at IncrementalLanguageService.assertHasFileName (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/@wessberg/rollup-plugin-ts/src/service/language-service/incremental-language-service.ts:397:11)
    at IncrementalLanguageService.getScriptSnapshot (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/@wessberg/rollup-plugin-ts/src/service/language-service/incremental-language-service.ts:311:21)
    at HostCache.createEntry (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:138963:44)
    at HostCache.getOrCreateEntryByPath (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:138986:58)
    at getOrCreateSourceFileByPath (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:139320:66)
    at Object.getOrCreateSourceFile [as getSourceFile] (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:139313:24)
    at findSourceFile (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:101542:29)
    at /home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:101419:85
    at getSourceFileFromReferenceWorker (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:101386:34)
    at processSourceFile (/home/c00513733/opensource-owner/intl-relative-time-format-1.0.6/node_modules/typescript/lib/typescript.js:101419:13)
```
Any suggestion on how to fix this? Thanks a lot!

**Comment by chenqy930** [comment]
Figured out the reason is a higher version of typescript than the one required in package.json.   

In package.json, it saids "typescript": "^3.3.3", so when running npm install, version 3.9.7 is installed.   

Install typescript's version 3.3.3 solved this problem!
